spotifyTrackVars <- c('track.s.id',
                      'track.s.title',
                      'track.s.artists',
                      'track.s.firstartist.id',
                      'track.s.firstartist.name',
                      'track.s.explicit',
                      'track.s.popularity',
                      'track.s.isrc',
                      'track.s.duration',
                      'track.s.durationms',
                      'track.s.albumposition',
                      'track.s.danceability',
                      'track.s.energy',
                      'track.s.key',
                      'track.s.loudness',
                      'track.s.mode',
                      'track.s.speechiness',
                      'track.s.acousticness',
                      'track.s.instrumentalness',
                      'track.s.liveness',
                      'track.s.valence',
                      'track.s.tempo',
                      'track.s.timesignature',
                      'album.s.id',
                      'album.s.title')

musicbrainzTrackVars <- c(
  'track.mb.id',
  'track.mb.title',
  'track.mb.quality',
  'track.mb.foundbyisrc',
  'track.mb.artistlist',
  'track.mb.firstartist.id',
  'track.mb.firstartist.name',
  'track.mb.firstartist.quality',
  'track.mb.releases',
  'track.mb.genres',
  'track.mb.topgenre')

spotifyAlbumVars <- c('album.s.id',
                      'album.s.title',
                      'album.s.type',
                      'album.s.upc',
                      'album.s.totaltracks',
                      'album.s.releasedate',
                      'album.s.releaseyear',
                      'album.s.label',
                      'album.s.popularity',
                      'album.s.firstartist.id',
                      'album.s.firstartist.name')

musicbrainzAlbumVars <- c('album.mb.id',
                          'album.mb.title',
                          'album.mb.quality',
                          'album.mb.foundbyupc',
                          'album.mb.firstartist.id',
                          'album.mb.firstartist.name',
                          'album.mb.firstartist.quality',
                          'album.mb.genres',
                          'album.mb.topgenre',
                          'album.mb.language')

spotifyArtistVars <- c(    'artist.s.id',
                           'artist.s.name',
                           'artist.s.genres',
                           'artist.s.topgenre',
                           'artist.s.popularity',
                           'artist.s.followers')

musicbrainzArtistVars <- c('artist.mb.id',
                           'artist.mb.name',
                           'artist.mb.quality',
                           'artist.mb.type',
                           'artist.mb.gender',
                           'artist.mb.origin',
                           'artist.mb.area',
                           'artist.mb.birth',
                           'artist.mb.birthyear',
                           'artist.mb.death',
                           'artist.mb.deathyear',
                           'artist.mb.dead',
                           'artist.mb.genres',
                           'artist.mb.foundbyid',
                           'artist.mb.topgenre')

spotifyAllVars <- union(spotifyTrackVars, spotifyAlbumVars) %>% union(spotifyArtistVars)
musicbrainzAllVars <- union(musicbrainzTrackVars, musicbrainzAlbumVars) %>% union(musicbrainzArtistVars)

correctTypesAll <- c(
  track.s.id	= 'character',
  track.s.title	= 'character',
  track.s.artists	= 'list',
  track.s.firstartist.id	= 'character',
  track.s.firstartist.name	= 'character',
  track.s.explicit = 'logical',
  track.s.popularity	= 'integer',
  track.s.isrc	= 'character',
  track.s.durationms	= 'integer',
  track.s.duration	= 'numeric',
  track.s.albumposition	= 'integer',
  track.s.danceability	= 'numeric',
  track.s.energy	= 'numeric',
  track.s.key	= 'character',
  track.s.loudness	= 'numeric',
  track.s.mode	= 'character',
  track.s.speechiness	= 'numeric',
  track.s.acousticness	= 'numeric',
  track.s.instrumentalness	= 'numeric',
  track.s.liveness	= 'numeric',
  track.s.valence	= 'numeric',
  track.s.tempo	= 'numeric',
  track.s.timesignature	= 'character',
  track.mb.id	= 'character',
  track.mb.title	= 'character',
  track.mb.quality	= 'numeric',
  track.mb.foundbyisrc = 'logical',
  track.mb.artistlist	= 'list',
  track.mb.firstartist.id = 'character',
  track.mb.firstartist.name = 'character',
  track.mb.firstartist.quality = 'numeric',
  track.mb.releases	= 'list',
  track.mb.genres	= 'list',
  track.mb.topgenre	= 'character',
  track.mb.combinedgenre	= 'character',
  artist.s.id	= 'character',
  artist.s.name	= 'character',
  artist.s.genres	= 'list',
  artist.s.topgenre	= 'character',
  artist.s.popularity	= 'integer',
  artist.s.followers	= 'integer',
  artist.mb.id	= 'character',
  artist.mb.foundbyid = 'logical',
  artist.mb.name	= 'character',
  artist.mb.quality	= 'numeric',
  artist.mb.type	= 'character',
  artist.mb.gender	= 'character',
  artist.mb.origin	= 'character',
  artist.mb.area	= 'character',
  artist.mb.birth	= 'Date',
  artist.mb.birthyear	= 'integer',
  artist.mb.death	= 'Date',
  artist.mb.deathyear	= 'integer',
  artist.mb.dead	= 'logical',
  artist.mb.genres	= 'list',
  artist.mb.topgenre	= 'character',
  artist.mb.combinedgenre	= 'character',
  album.s.id	= 'character',
  album.s.title	= 'character',
  album.s.type	= 'character',
  album.s.upc	= 'character',
  album.s.totaltracks	= 'integer',
  album.s.releasedate	= 'Date',
  album.s.releaseyear	= 'integer',
  album.s.label	= 'character',
  album.s.popularity	= 'integer',
  album.s.firstartist.id = 'character',
  album.s.firstartist.name = 'character',
  album.mb.id	= 'character',
  album.mb.title	= 'character',
  album.mb.quality	= 'numeric',
  album.mb.foundbyupc = 'logical',
  album.mb.language	= 'character',
  album.mb.firstartist.name = 'character',
  album.mb.firstartist.quality = 'numeric',
  album.mb.genres	= 'list',
  album.mb.topgenre	= 'character',
  album.mb.combinedgenre	= 'character'
)

spotifyAudioanalysisVars <- c('track.s.id',
                              'track.s.tempoconfidence',
                              'track.s.timesignatureconfidence',
                              'track.s.keyconfidence',
                              'track.s.modeconfidence',
                              'track.s.bars',
                              'track.s.beats',
                              'track.s.sections',
                              'track.s.segments',
                              'track.s.tatums',
                              'track.s.synchstring',
                              'track.s.rhythmstring',
                              'track.s.echoprintstring',
                              'track.s.codestring')

correctTypesAudioanalysis <- c(
  track.s.id	= 'character',
  track.s.tempoconfidence	= 'numeric',
  track.s.timesignatureconfidence	= 'numeric',
  track.s.keyconfidence	= 'numeric',
  track.s.modeconfidence	= 'numeric',
  track.s.bars = 'list',
  track.s.beats = 'list',
  track.s.sections = 'list',
  track.s.segments = 'list',
  track.s.tatums = 'list',
  track.s.synchstring = 'character',
  track.s.rhythmstring = 'character',
  track.s.echoprintstring = 'character',
  track.s.codestring = 'character'
)

discogsAlbumVars <- c('album.dc.id', 'album.dc.title', 'album.dc.genres', 'album.dc.styles',
                      'album.dc.firstgenre', 'album.dc.firststyle',
                      'album.dc.quality', 'artist.dc.name', 'artist.dc.quality')

geniusLyricsVars <- c('track.g.id', 'track.g.title', 'track.g.quality',
                      'artist.g.id', 'artist.g.name', 'artist.g.quality',
                      'track.g.lyrics', 'track.g.lyricsstate')

deezerTrackVars <- c('track.dz.id', 'track.dz.title', 'track.dz.isrc', 'track.dz.duration', 'track.dz.rank',
                     'track.dz.explicit', 'track.dz.explicitinfo', 'track.dz.tempo', 'track.dz.loudness', 'track.dz.quality',
                     'track.dz.firstartist.id', 'track.dz.firstartist.name', 'track.dz.firstartist.quality',
                     'track.dz.album.id', 'track.dz.album.title', 'track.dz.album.quality')

deezerAlbumVars <- c('album.dz.id', 'album.dz.title', 'album.dz.upc', 'album.dz.totaltracks', 'album.dz.duration',
                     'album.dz.follower', 'album.dz.releasedate', 'album.dz.type', 'album.dz.explicitlyrics',
                     'album.dz.explicitlyricsinfo', 'album.dz.explicitcoverinfo', 'album.dz.label',
                     'album.dz.firstgenre.id', 'album.dz.firstgenre.name', 'album.dz.genres', 'album.dz.quality',
                     'album.dz.firstartist.id', 'album.dz.firstartist.name','album.dz.firstartist.quality')

deezerArtistVars <- c('artist.dz.id', 'artist.dz.name', 'artist.dz.follower', 'artist.dz.nalbums',
                       'artist.dz.quality', 'artist.dz.toptracks')

deezerAllVars <- c(deezerTrackVars,
                   'track.dz.album.id', 'track.dz.album.title', 'track.dz.album.upc', 'track.dz.album.totaltracks',
                   'track.dz.album.duration', 'track.dz.album.follower', 'track.dz.album.releasedate', 'track.dz.album.type',
                   'track.dz.album.explicitlyrics', 'track.dz.album.explicitlyricsinfo', 'track.dz.album.explicitcoverinfo',
                   'track.dz.album.label', 'track.dz.album.firstgenre.id', 'track.dz.album.firstgenre.name',
                   'track.dz.album.genres',
                   'track.dz.firstartist.follower', 'track.dz.firstartist.nalbums', 'track.dz.firstartist.toptracks')

acousticbrainzTrackVarsHighlevel <- c(
  'track.ab.id', 'track.ab.danceability', 'track.ab.gender',
  'track.ab.genredortmund', 'track.ab.genreelectronic', 'track.ab.genrerosamerica',
  'track.ab.genretzanetakis', 'track.ab.ismir04rhythm', 'track.ab.acoustic',
  'track.ab.aggressive', 'track.ab.electronic', 'track.ab.happy',
  'track.ab.party', 'track.ab.relaxed', 'track.ab.sad',
  'track.ab.mirex', 'track.ab.timbre', 'track.ab.tonalatonal',
  'track.ab.voiceinstrumental', 'track.ab.p.danceable', 'track.ab.p.female',
  'track.ab.p.acoustic', 'track.ab.p.aggressive', 'track.ab.p.electronic',
  'track.ab.p.happy', 'track.ab.p.party', 'track.ab.p.relaxed',
  'track.ab.p.sad', 'track.ab.p.bright', 'track.ab.p.tonal',
  'track.ab.p.voice', 'track.ab.p.drtmd.alternative', 'track.ab.p.drtmd.blues',
  'track.ab.p.drtmd.electronic', 'track.ab.p.drtmd.folk.country', 'track.ab.p.drtmd.funk.soul.rnb',
  'track.ab.p.drtmd.jazz', 'track.ab.p.drtmd.pop', 'track.ab.p.drtmd.rap.hiphop',
  'track.ab.p.drtmd.rock', 'track.ab.p.eltrc.ambient', 'track.ab.p.eltrc.drumandbass',
  'track.ab.p.eltrc.house', 'track.ab.p.eltrc.techno', 'track.ab.p.eltrc.trance',
  'track.ab.p.rosa.classical', 'track.ab.p.rosa.dance', 'track.ab.p.rosa.hiphop',
  'track.ab.p.rosa.jazz', 'track.ab.p.rosa.pop', 'track.ab.p.rosa.rhythmandblues',
  'track.ab.p.rosa.rock', 'track.ab.p.rosa.speech', 'track.ab.p.tzntk.blues',
  'track.ab.p.tzntk.classical', 'track.ab.p.tzntk.country', 'track.ab.p.tzntk.disco',
  'track.ab.p.tzntk.hiphop', 'track.ab.p.tzntk.jazz', 'track.ab.p.tzntk.metal',
  'track.ab.p.tzntk.pop', 'track.ab.p.tzntk.reggae', 'track.ab.p.tzntk.rock',
  'track.ab.p.ismir.chachacha', 'track.ab.p.ismir.jive', 'track.ab.p.ismir.quickstep',
  'track.ab.p.ismir.rumbaamerican', 'track.ab.p.ismir.rumbainternational', 'track.ab.p.ismir.rumbamisc',
  'track.ab.p.ismir.samba', 'track.ab.p.ismir.tango', 'track.ab.p.ismir.viennesewaltz',
  'track.ab.p.ismir.waltz', 'track.ab.p.mirex.aggressive', 'track.ab.p.mirex.humorous',
  'track.ab.p.mirex.literate', 'track.ab.p.mirex.passionate', 'track.ab.p.mirex.rollicking')

acousticbrainzTrackVarsLowlevel <- c(
  'track.ab.rhythm.tempo', 'track.ab.rhythm.danceability', 'track.ab.rhythm.onsetrate',
  'track.ab.low.loudness', 'track.ab.low.dynamiccomplexity', 'track.ab.tonal.chordchangerate',
  'track.ab.tonal.key', 'track.ab.tonal.chordsnumberrate', 'track.ab.tonal.mode',
  'track.ab.tonal.keystrength'
)

acousticbrainzTrackVars <- union(acousticbrainzTrackVarsHighlevel, acousticbrainzTrackVarsLowlevel)
